# Generated by Django 2.2.6 on 2019-11-12 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0003_auto_20191109_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_info',
            name='fieldofinterest',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate_info',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate_info',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='type',
            field=models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship'), ('4', 'freelance'), ('5', 'temporary')], default='3', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
