# Generated by Django 2.2.6 on 2019-11-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0004_auto_20191112_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_info',
            name='image',
            field=models.ImageField(default=None, upload_to='profile_pics'),
        ),
    ]
